# Web??????
server.port=8080

spring.profiles.active=${APP_PROFILE:minimax}

spring.data.mongodb.uri=mongodb://localhost:27017/chat_memory_db

logging.level.root=INFO
logging.level.dev.langchain4j=INFO